###############################################################################
# infra/variables.tf
#
# PURPOSE: Declares all input variables. No sensitive values here — those are
#          generated by the secrets module (Secrets Manager) or live in
#          terraform.tfvars (gitignored) for non-sensitive config only.
###############################################################################

# ── General ───────────────────────────────────────────────────────────────────

variable "aws_region" {
  description = "AWS region for all resources."
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Deployment environment. Controls naming and tagging."
  type        = string
  default     = "dev"

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "environment must be one of: dev, staging, prod."
  }
}

variable "project_name" {
  description = "Short project identifier used as a prefix in all resource names."
  type        = string
  default     = "vaultbridge"
}

# ── Networking ────────────────────────────────────────────────────────────────

variable "vpc_cidr" {
  description = "CIDR block for the VPC."
  type        = string
  default     = "10.0.0.0/16"
}

variable "public_subnet_cidrs" {
  description = "CIDR blocks for the two public subnets (one per AZ)."
  type        = list(string)
  default     = ["10.0.1.0/24", "10.0.2.0/24"]
}

variable "private_subnet_cidrs" {
  description = "CIDR blocks for the two private subnets (one per AZ). RDS lives here."
  type        = list(string)
  default     = ["10.0.11.0/24", "10.0.12.0/24"]
}

variable "availability_zones" {
  description = "Two AZs to spread subnets across for high availability."
  type        = list(string)
  default     = ["us-east-1a", "us-east-1b"]
}

# ── Compute ───────────────────────────────────────────────────────────────────

variable "ec2_instance_type" {
  description = "EC2 instance type for the application server."
  type        = string
  default     = "t3.micro"
}

variable "key_pair_name" {
  description = "Name of the EC2 Key Pair for SSH access. Must already exist in AWS."
  type        = string
}

variable "allowed_ssh_cidr" {
  description = "CIDR block permitted to SSH into the EC2 instance. Use your IP, not 0.0.0.0/0."
  type        = string

  validation {
    condition     = can(cidrhost(var.allowed_ssh_cidr, 0))
    error_message = "allowed_ssh_cidr must be a valid CIDR block (e.g. 203.0.113.5/32)."
  }
}

variable "volume_size" {
  description = "Size of EC2 storage volume"
  type        = number
  default     = 20
}

variable "volume_type" {
  description = "The type of EC2 storage volume"
  type        = string
  default     = "gp3"
}

# ── Database ──────────────────────────────────────────────────────────────────

variable "db_instance_class" {
  description = "RDS instance class."
  type        = string
  default     = "db.t3.micro"
}

variable "db_name" {
  description = "Name of the initial database to create."
  type        = string
  default     = "vaultbridge"
}

variable "db_config" {
  description = "RDS engine and storage configuration."
  type = object({
    engine                = string
    engine_version        = string
    allocated_storage     = number
    max_allocated_storage = number
  })
  default = {
    engine                = "postgres"
    engine_version        = "16"
    allocated_storage     = 20
    max_allocated_storage = 100
  }
}

variable "db_selected_number" {
  description = "A number set for db configurations"
  type        = number
  default     = 7
}

# ── Secrets Manager ───────────────────────────────────────────────────────────

# secret_rotation_days is reserved for when rotation is enabled.
# See modules/secrets/main.tf for instructions on enabling rotation.
# variable "secret_rotation_days" {
#   description = "How often (in days) Secrets Manager automatically rotates the DB password."
#   type        = number
#   default     = 30
# }


